name: CMake CI on Ubuntu with Clang and GTK3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake make libgtk-3-dev

    - name: Build with CMake and Clang
      run: |
        export CC=clang
        export CXX=clang++
        cmake -S . -B build
        cmake --build build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-build-artifacts
        path: build/
